[package]
name = "cagada-finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.1"
clap = { version = "4.0", features = ["derive"] }
serde = "1.0.155"
toml = "0.7.3"
